spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    driver-class-name: "org.postgresql.Driver"
    username: "postgres"
    password: "postgres"
  liquibase:
    change-log: liquibase/changelog.xml
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate